### ISSUE TITLE
messages d'erreur

### ISSUE THREAD

**Issue by GeorgeDelSims** [GeorgeDelSims/Minishell#157]
minishell> < fdhf dafds 
minishell: fdhf: No such file or directory
minishell: <: command not found

Il faudrait un seul message d'erreur dans ce cas, le premier.

**Comment by Mathlamass74** [comment]
le problème vient de init_paths, a la fin dans la boucle on renvoie command not found mais en réalité il faut juste return car le command not foule on le gère déjà, motifs faites : 
remplacé ca :

int	init_paths(t_data *d)
{
	t_liste	*tmp;

	tmp = d->list;
	init_bin_paths(tmp);
	if (access_utils(d, d->list->cmd, 1) == 2)
		return (tmp->cmd_path = ft_strdup(d->list->cmd), 0);
	while (tmp)
	{
		if (tmp->cmd && is_builtin(tmp->cmd) == CMD && d->path_unset == 0)
		{
			if (check_access_for_non_builtins(d, tmp) == -1)
				return (-1);
		}
		else if (tmp->cmd && is_builtin(tmp->cmd) == BUILTIN)
			tmp->cmd_path = NULL;
		else if (ft_strcmp(tmp->token->content, "<<") == 0 && tmp->token->next
			&& !tmp->token->next->next)
			return (-1);
		else
			return (ft_error(d, tmp->token->content, NO_CMD, 127));
		tmp = tmp->next;
	}
	if (d->path_unset == 0)
		ft_free_array(d->bin_paths);
	return (0);
}

par ca :

		else
			return (-1);
